### ISSUE TITLE
Issue with view in vendor/geo-sv 

### ISSUE THREAD

**Issue by oddovid** [GeoSot/Laravel-EnvEditor#18]
Hi, 
I want to modify the display of published assets (`index.blade.php`) but nothing changes...

**Comment by GeoSot** [comment]
Hey @oddovid  please try to be more descriptive in order for me to be able to test and resolve this issue

**Comment by oddovid** [comment]
@GeoSot I modified the `resources/views/vendor/geo-sv/env-editor/index.blade.php` file, but no change. But when I do it in `vendor/geo-sot/laravel-env-editor/src/resources/view/index.blade.php` it works. I want to change the view without having to change it through package vendor. I've done `php artisan view:clear` but it still doesn't work...

**Comment by GeoSot** [comment]
@oddovid I've just applied a fix. #19 
please replace in your `composer.json` the package requirement, with `   "geo-sot/laravel-env-editor": "dev-main",`
and try:
`php artisan vendor:publish --provider="GeoSot\EnvEditor\ServiceProvider" --tag=views`

I think you should be ok now. Please give me a feedback in order to proceed with a realease

**Comment by oddovid** [comment]
@GeoSot thanks now it's solved :)
